spring:
  application:
    name: api-gateway  # Name of the application
  # Properties related to this microservice (api-gateway) is moved to central config server at URL:
  # https://github.com/saurabhkk55/ecommerce-config-server/blob/main/api-gateway.yml
  # Specifies the location of the configuration server for centralized configuration management.
  # The configuration server is expected to be running at the given URL (localhost on port 8888).
  config:
    import: configserver:http://localhost:8888
